Repository SergeiDemyanenko/PlatformaticaQA_02, pull requests merged in 2021-05, with the labels that each got.

#173 Refactor TatianaKTest Class
  src/test/java/TatianaKTest.java
Labels: approved

#198 IZ_Review Chain1 testCreateNewRecord() added
  src/test/java/EntityEventsChain1Test.java
Labels: need merge

#200 Test was created
  src/test/java/AlexFranchukTest.java
Labels: need merge

#202 Delete ignore
  src/test/java/GroupJPowerTest.java
Labels: need merge

#196 Stas champion test1
  src/test/java/StasChampionTest.java
Labels: need merge

#208 added EntityBoardTest: testDeleteRecord, testDeleteRecordFromRecyclingBin
  src/test/java/EntityBoardTest.java
  src/test/java/constants/EntityBoardConstants.java
Labels: ready to approve

#211 refactoring EntityBoardTest: added method start
  src/test/java/EntityBoardTest.java
Labels: ready to approve

#222 Refactor EntityBoardTest and EntityBoardConstants
  src/test/java/EntityBoardTest.java
  src/test/java/constants/EntityBoardConstants.java
Labels: ready to approve

#220 Refactor ProjectUtils: add method wait
  src/test/java/base/BaseTest.java
  src/test/java/utils/TestUtils.java
Labels: ready to approve

#239 Add findElement to BaseTest and refactoring
  src/test/java/EntityArithmeticFunctionTest.java
  src/test/java/EntityCalendarTest.java
  src/test/java/base/BaseTest.java
Labels: ready to approve

#242 refactoring BoardEntityTest
  src/test/java/EntityBoardTest.java
  src/test/java/base/BaseTest.java
  src/test/java/utils/TestUtils.java
Labels: ready to approve

#244 AT_016_Java | Entity > Calendar: Create and save a new record -double
  src/test/java/EntityArithmeticFunctionTest.java
  src/test/java/EntityCalendar1Test.java
  src/test/java/EntityCalendarTest.java
  src/test/java/EntityImportValuesTest.java
Labels: ready to approve

#245 refactoring BaseTest: method findElements moved to BaseTest
  src/test/java/EntityArithmeticFunctionTest.java
  src/test/java/EntityBoardTest.java
  src/test/java/EntityCalendarTest.java
  src/test/java/base/BaseTest.java
Labels: ready to approve

#249 EntityAssignTest: testReorderRecords
  src/test/java/EntityAssignTest.java
  src/test/java/EntityBoardDraftRecordTest.java
  src/test/java/constants/EntityAssignConstants.java
Labels: ready to approve

#267 Refactoring EntityCalendarTest
  src/test/java/EntityCalendarTest.java
Labels: ready to approve

#270 EntityArithmetic Inline: testViewCreatedRecord
  src/test/java/EntityArithmeticInlineTest.java
  src/test/java/constants/EntityArithmeticInlineConstants.java
Labels: ready to approve

#280 EntityParentCreateNewRecord
  src/test/java/EntityParentTest.java
  src/test/java/constants/EntityParentConstants.java
Labels: ready to approve

#286 EntityParent: testCancelRecord
  src/test/java/EntityParentTest.java
  src/test/java/constants/EntityParentConstants.java
Labels: ready to approve

#289 EntityParent: testDeleteRecord
  src/test/java/EntityParentTest.java
  src/test/java/constants/EntityParentConstants.java
Labels: ready to approve

#299 Delete Ignore
  src/test/java/EntityParentTest.java
  src/test/java/constants/EntityParentConstants.java
Labels: ready to approve
